---
Name: silverstripe-progressive-image
---
Silverstripe\Assets\Image:
  pil_filter_style: 'filter:blur(5px)'
  extensions:
    # image extensions
    - 'NSWDPC\ProgressiveImage\ProgressiveImageExtension'
PageController:
  extensions:
    # push script and style requirements
    - 'NSWDPC\ProgressiveImage\ProgressiveImageControllerExtension'
